sudo: required
services:
- docker
language: bash
env:
- SUFFIX=
- SUFFIX=-arm
branches:
  only:
  - /^v.+\-Xaegrek?.+/
script:
- if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- docker build -f Dockerfile${SUFFIX} -t Xaegrek/Hydrus-Docker:build .
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- TAG=${TRAVIS_TAG}${SUFFIX}
- docker tag Xaegrek/Hydrus-Docker:build Xaegrek/Hydrus-Docker:$TAG
- docker push Xaegrek/Hydrus-Docker:$TAG
