sudo: required
services:
- docker
language: bash
env:
- SUFFIX=
- SUFFIX=-arm
branches:
  only:
  - /^v.+\-blott?.+/
script:
- if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- docker build -f Dockerfile${SUFFIX} -t blott/hydrus:build .
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- TAG=${TRAVIS_TAG}${SUFFIX}
- docker tag blott/hydrus:build blott/hydrus:$TAG
- docker push blott/hydrus:$TAG
