os:
  - osx
  - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install opencv wxpython ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install python2.7-dev python-numpy python-opencv python-wxgtk2.8 ; fi

install:
  - pip install -r requirements.txt

script:
  - pyinstaller --windowed --hidden-import appdirs --hidden-import six --hidden-import packaging --hidden-import packaging.version --hidden-import packaging.specifiers --hidden-import packaging.requirements --name="client" client.py
  - pyinstaller --hidden-import appdirs --hidden-import six --hidden-import packaging --hidden-import packaging.version --hidden-import packaging.specifiers --hidden-import packaging.requirements --name="server" server.py
