FROM armhf/python:2.7-alpine

COPY tmp/qemu-arm-static /usr/bin/qemu-arm-static

WORKDIR /hydrus/

RUN apk add --update build-base libjpeg-turbo jpeg-dev linux-headers zlib-dev libffi libffi-dev openssl-dev ffmpeg py-numpy \
    && ln -s /usr/include/locale.h /usr/include/xlocale.h \
    && pip install pyyaml beautifulsoup4 lz4 psutil Send2Trash twisted hsaudiotag PyPDF2 Pillow pycrypto PyOpenSSL service_identity \
    && apk del build-base jpeg-dev linux-headers zlib-dev libffi-dev openssl-dev \
    && rm -rf ~/.cache

COPY ./bin/ /hydrus/bin/
COPY ./db/ /hydrus/db/
COPY ./help/ /hydrus/help/
COPY ./include/ /hydrus/include/
COPY ./lib/ /hydrus/lib/
COPY ./static/ /hydrus/static/
COPY ./client.py /hydrus/client.py
COPY ./server.py /hydrus/server.py

VOLUME /hydrus/db/

EXPOSE 45870

CMD ["python2", "server.py"]
